package com.calculator.grapher;

import static com.calculator.commoncalculator.Ui.setNumberTexting;
import java.text.DecimalFormat;

public class VariablePanel extends javax.swing.JPanel {

    private double value = 1;
    private double max = 5;
    private double min = -5;
    private double step = 0.1;

    public VariablePanel() {
        initComponents();
        setNumberTexting(jTextField1, jButton1);
        setNumberTexting(jTextField2, jButton2);
        setNumberTexting(jTextField3, jButton3);
        setNumberTexting(jTextField4, jButton4);
        update();
        
    }

    private void update() {

        jTextField1.setText(parseDouble(value));
        jTextField2.setText(parseDouble(min));
        jTextField3.setText(parseDouble(step));
        jTextField4.setText(parseDouble(max));
        slider.setValue((int) (((value-min) *100/ (max - min))));
    }

    public double getValue() {
        return value;
    }

    public void setValue(double value) {
        DecimalFormat df = new DecimalFormat(String.format("#.%s", "#".repeat((int) Math.abs(Math.log10(getStep())-1))));
        value=Double.parseDouble(df.format(value));
        double m=Double.parseDouble(df.format(value%getStep()));
        if(m==0){
            this.value=value;
        }else{
            double amin=value-m<getMin()?getMin():value-m;
            double amax=(value-m)+getStep()>getMax()?getMax():(value-m)+getStep();
            if((amax-amin)<step){
                m=amax-amin;
                this.value=(value-amin)>m/2?amax:amin;
            }else{
                this.value=m<getStep()/2?amin:amax;
            }
        }
        if (value > max) {
            setMax(value);
        }
        if (value < min) {
            setMin(value);
        }
    }

    public double getMax() {
        return max;
    }

    public void setMax(double max) {
        this.max = max;
        if (max < min) {
            setMin(max - 10);
        }
        if (max < value) {
            setValue(max);
        }
    }

    public double getMin() {
        return min;
    }

    public void setMin(double min) {
        this.min = min;
        if (min > max) {
            setMax(min+10);
        }
        if (min > value) {
            setValue(min);
        }
    }

    public double getStep() {
        return step;
    }

    public void setStep(double step) {
        this.step = step;
    }

    private static String parseDouble(double d) {
        if (d!=0&&Math.abs(Math.log10(d)) > 6) {
            return new DecimalFormat("0.######E0").format(d);
        }
        return new DecimalFormat("#.##########").format(d);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        slider = new javax.swing.JSlider();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Value");
        jPanel2.add(jLabel1);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("1");
        jTextField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 1));
        jTextField1.setMaximumSize(new java.awt.Dimension(2147483647, 20));
        jTextField1.setScrollOffset(5);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);

        jButton1.setText("X");
        jPanel1.add(jButton1);

        jPanel2.add(jPanel1);

        add(jPanel2);

        slider.setToolTipText("");
        slider.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sliderMouseDragged(evt);
            }
        });
        add(slider);

        jButton5.setText("▲");
        jButton5.setAlignmentX(0.5F);
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jPanel8.setAlignmentX(1.0F);
        jPanel8.setAlignmentY(0.0F);
        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Min");
        jPanel8.add(jLabel4);

        jPanel9.setAlignmentX(0.0F);
        jPanel9.setAlignmentY(0.0F);
        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.X_AXIS));

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("-5");
        jTextField2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 1));
        jTextField2.setMaximumSize(new java.awt.Dimension(2147483647, 20));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel9.add(jTextField2);

        jButton2.setText("X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton2);

        jPanel8.add(jPanel9);

        jPanel4.add(jPanel8);

        jPanel11.setAlignmentX(1.0F);
        jPanel11.setAlignmentY(0.0F);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Step");
        jPanel11.add(jLabel5);

        jPanel12.setAlignmentX(0.0F);
        jPanel12.setAlignmentY(0.0F);
        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.X_AXIS));

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("0.1");
        jTextField3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 1));
        jTextField3.setMaximumSize(new java.awt.Dimension(2147483647, 20));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel12.add(jTextField3);

        jButton3.setText("X");
        jPanel12.add(jButton3);

        jPanel11.add(jPanel12);

        jPanel4.add(jPanel11);

        jPanel13.setAlignmentX(1.0F);
        jPanel13.setAlignmentY(0.0F);
        jPanel13.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Max");
        jPanel13.add(jLabel6);

        jPanel14.setAlignmentX(1.0F);
        jPanel14.setAlignmentY(0.0F);
        jPanel14.setLayout(new javax.swing.BoxLayout(jPanel14, javax.swing.BoxLayout.X_AXIS));

        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("5");
        jTextField4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 1));
        jTextField4.setMaximumSize(new java.awt.Dimension(2147483647, 20));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel14.add(jTextField4);

        jButton4.setText("X");
        jPanel14.add(jButton4);

        jPanel13.add(jPanel14);

        jPanel4.add(jPanel13);

        jPanel3.add(jPanel4);

        add(jPanel3);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        try {
            Double v = Double.valueOf(jTextField1.getText());
            setValue(v);
            update();
        } catch (NumberFormatException e) {
            jTextField1.setText(parseDouble(getValue()));
        }
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        try {
            Double v = Double.valueOf(jTextField2.getText());
            setMin(v);
            update();
        } catch (NumberFormatException e) {
            jTextField2.setText(parseDouble(getMin()));
        }
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        try {
            Double v = Double.valueOf(jTextField3.getText());
            setStep(Math.abs(v));
            update();
        } catch (NumberFormatException e) {
            jTextField3.setText(parseDouble(getStep()));
        }
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        try {
            Double v = Double.valueOf(jTextField4.getText());
            setMax(v);
            update();
        } catch (NumberFormatException e) {
            jTextField4.setText(parseDouble(getMax()));
        }
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jPanel3.setVisible(jButton5.getText().equals("▼"));
        revalidate();
        repaint();
        jButton5.setText(jButton5.getText().equals("▼")?"▲":"▼");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void sliderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sliderMouseDragged
        setValue(((slider.getValue()/100.)*(getMax()-getMin()))+getMin());
        System.out.println("slider\t"+(((slider.getValue()/100.)*(getMax()-getMin()))+getMin()));
        System.out.println("value\t "+getValue()+"\n");
        update();
    }//GEN-LAST:event_sliderMouseDragged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JSlider slider;
    // End of variables declaration//GEN-END:variables
}
