/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.codes;

/**
 *
 * @author adith
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        binKeyPanel1 = new javax.swing.JPanel();
        bin5 = new javax.swing.JButton();
        bin6 = new javax.swing.JButton();
        bin7 = new javax.swing.JButton();
        bin8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        binKeyPanel1.setMinimumSize(new java.awt.Dimension(80, 55));

        bin5.setBackground(jPanel12.getBackground());
        bin5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bin5.setText("0");
        bin5.setBorder(null);
        bin5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bin5ActionPerformed(evt);
            }
        });

        bin6.setBackground(jPanel12.getBackground());
        bin6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bin6.setText("0");
        bin6.setBorder(null);
        bin6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bin6ActionPerformed(evt);
            }
        });

        bin7.setBackground(jPanel12.getBackground());
        bin7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bin7.setText("0");
        bin7.setBorder(null);
        bin7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bin7ActionPerformed(evt);
            }
        });

        bin8.setBackground(jPanel12.getBackground());
        bin8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bin8.setText("0");
        bin8.setBorder(null);
        bin8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bin8ActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("4");

        javax.swing.GroupLayout binKeyPanel1Layout = new javax.swing.GroupLayout(binKeyPanel1);
        binKeyPanel1.setLayout(binKeyPanel1Layout);
        binKeyPanel1Layout.setHorizontalGroup(
            binKeyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, binKeyPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(binKeyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(binKeyPanel1Layout.createSequentialGroup()
                        .addComponent(bin8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bin7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bin6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bin5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        binKeyPanel1Layout.setVerticalGroup(
            binKeyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(binKeyPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(binKeyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bin8)
                    .addComponent(bin7)
                    .addComponent(bin6)
                    .addComponent(bin5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(244, Short.MAX_VALUE)
                .addComponent(binKeyPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(169, Short.MAX_VALUE)
                .addComponent(binKeyPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bin5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bin5ActionPerformed
        setBinKey(bin5);
    }//GEN-LAST:event_bin5ActionPerformed

    private void bin6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bin6ActionPerformed
        setBinKey(bin6);
    }//GEN-LAST:event_bin6ActionPerformed

    private void bin7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bin7ActionPerformed
        setBinKey(bin7);
    }//GEN-LAST:event_bin7ActionPerformed

    private void bin8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bin8ActionPerformed
        setBinKey(bin8);
    }//GEN-LAST:event_bin8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bin5;
    public javax.swing.JButton bin6;
    public javax.swing.JButton bin7;
    public javax.swing.JButton bin8;
    public javax.swing.JPanel binKeyPanel1;
    public javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
