package com.calculator.commonCalculator.memory;

import com.calculate.CNumber;
import com.calculator.commonCalculator.Ui;
import java.awt.Color;
import java.awt.Container;

/**
 *
 * @author AW Developer
 */
public abstract class MemoryCell extends javax.swing.JPanel {

    protected CNumber value;
    public static CNumber INCREMENT = CNumber.parseNumber(0);
    public static int CURRENT_CELL_COUNT = 0;

    /**
     * Creates new form HistoryCell
     */
    public MemoryCell(CNumber value) {
        CURRENT_CELL_COUNT++;
        initComponents();
        this.value = value;
        INCREMENT = value;
        setValue(value);
        java.awt.event.MouseAdapter listner = new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseEnter();
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseExit();
            }
        };
        jButton1.addMouseListener(listner);
        jButton2.addMouseListener(listner);
        jButton3.addMouseListener(listner);
        jPanel1.addMouseListener(listner);
        jPanel2.addMouseListener(listner);
        jTextArea1.addMouseListener(listner);
        jScrollPane1.addMouseListener(listner);
        addMouseListener(listner);
    }

    public void setValue(CNumber num) {
        jTextArea1.setText(num.getNumberString());
    }

    public void increment() {
        addValue(INCREMENT);
    }

    public void decrement() {
        substractValue(INCREMENT);
    }

    public void substractValue(CNumber n) {
        value = value.substract(n);
        setValue(value);
    }

    public void addValue(CNumber n) {
        value = value.add(n);
        setValue(value);
    }
    
    public CNumber getValue(){
        return value;
    }

    public abstract void memoryItemClicked(CNumber num);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(300, 100));
        setMinimumSize(new java.awt.Dimension(230, 50));
        setPreferredSize(new java.awt.Dimension(230, 50));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setLayout(new java.awt.CardLayout(5, 5));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setToolTipText("");
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setEnabled(false);
        jScrollPane1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jScrollPane1.setInheritsPopupMenu(true);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(1);
        jTextArea1.setTabSize(10);
        jTextArea1.setText("0");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setAlignmentX(0.0F);
        jTextArea1.setAlignmentY(0.0F);
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, "card2");

        add(jPanel1);
        jButton1.setVisible(false);
        jButton2.setVisible(false);
        jButton3.setVisible(false);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButton1.setText("MC");
        jButton1.setToolTipText("Clear memory item");
        jButton1.setAlignmentX(1.0F);
        jButton1.setBorder(null);
        jButton1.setMaximumSize(new java.awt.Dimension(50, 30));
        jButton1.setMinimumSize(new java.awt.Dimension(50, 30));
        jButton1.setPreferredSize(new java.awt.Dimension(50, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton2.setText("M+");
        jButton2.setToolTipText("Add memory item");
        jButton2.setAlignmentX(1.0F);
        jButton2.setBorder(null);
        jButton2.setMaximumSize(new java.awt.Dimension(50, 30));
        jButton2.setMinimumSize(new java.awt.Dimension(50, 30));
        jButton2.setPreferredSize(new java.awt.Dimension(50, 30));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        jButton3.setText("M-");
        jButton3.setToolTipText("Substract memory item");
        jButton3.setAlignmentX(1.0F);
        jButton3.setBorder(null);
        jButton3.setMaximumSize(new java.awt.Dimension(50, 30));
        jButton3.setMinimumSize(new java.awt.Dimension(50, 30));
        jButton3.setPreferredSize(new java.awt.Dimension(50, 30));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        increment();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        decrement();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CURRENT_CELL_COUNT--;
        Container parent = getParent();
        if (getParent() != null) {
            MemoryPanel.cells.remove(this);
            parent.remove(this);
            parent.revalidate();
            parent.repaint();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        int h1 = Ui.wrapHeight(jTextArea1);
        if (h1 != -1) {
            Ui.setSize(jTextArea1, 300, h1 + 30);
            Ui.setSize(this, 300, h1 + 100);

        }
    }//GEN-LAST:event_formComponentResized

    public void mouseEnter() {
        Color c = Ui.APP_HOVER;
        jTextArea1.setBackground(c);
        jPanel1.setBackground(c);
        jPanel2.setBackground(c);
        jButton1.setVisible(true);
        jButton2.setVisible(true);
        jButton3.setVisible(true);
    }

    public void mouseExit() {
        jTextArea1.setBackground(getBackground());
        jPanel1.setBackground(getBackground());
        jPanel2.setBackground(getBackground());
        jButton1.setVisible(false);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
