package com.calculator.commoncalculator.memory;

import com.amath.advacedmath.calculate.CNumber;
import com.calculator.commoncalculator.CommonNumberPanel;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;

public class MemoryBar extends javax.swing.JPanel {

    public final MemoryPanel memoryPanel;
    CommonNumberPanel numberPanel;

    public MemoryBar(MemoryPanel memoryPanel, CommonNumberPanel numberPanel) {
        initComponents();
        this.memoryPanel = memoryPanel;
        this.numberPanel = numberPanel;
        this.memoryPanel.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentShown(ComponentEvent e) {
                jButton11.setVisible(true);
            }

            @Override
            public void componentHidden(ComponentEvent e) {
                jButton11.setVisible(false);
            }
        });
    }

    public void memoryStore() {
        memoryPanel.newMemory(new MemoryCell(numberPanel.getNumber()) {
            @Override
            public void memoryItemClicked(CNumber num) {
                numberPanel.setNumber(num);
            }
        });
    }

    public void memoryRecall() {
        numberPanel.setNumber(MemoryPanel.cells.get(0).getValue());
    }

    public void memoryAdd() {
        MemoryPanel.cells.get(0).addValue(numberPanel.getNumber());
    }

    public void memorySubstract() {
        MemoryPanel.cells.get(0).substractValue(numberPanel.getNumber());
    }

    public void clearAllMemory() {
        memoryPanel.clearAllMemory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        jDialog1.setUndecorated(true);
        jDialog1.addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                jDialog1WindowLostFocus(evt);
            }
        });
        jDialog1.getContentPane().setLayout(new java.awt.CardLayout());

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jButton6.setBackground(getBackground());
        jButton6.setText("MC");
        jButton6.setBorder(null);
        jButton6.setMaximumSize(new java.awt.Dimension(200, 200));
        jButton6.setMinimumSize(new java.awt.Dimension(40, 30));
        jButton6.setPreferredSize(new java.awt.Dimension(50, 30));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6);

        jButton8.setBackground(getBackground());
        jButton8.setText("MR");
        jButton8.setBorder(null);
        jButton8.setMaximumSize(new java.awt.Dimension(200, 200));
        jButton8.setMinimumSize(new java.awt.Dimension(40, 30));
        jButton8.setPreferredSize(new java.awt.Dimension(50, 30));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        add(jButton8);

        jButton7.setBackground(getBackground());
        jButton7.setText("M+");
        jButton7.setBorder(null);
        jButton7.setMaximumSize(new java.awt.Dimension(200, 200));
        jButton7.setMinimumSize(new java.awt.Dimension(40, 30));
        jButton7.setPreferredSize(new java.awt.Dimension(50, 30));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        add(jButton7);

        jButton9.setBackground(getBackground());
        jButton9.setText("M-");
        jButton9.setBorder(null);
        jButton9.setMaximumSize(new java.awt.Dimension(200, 200));
        jButton9.setMinimumSize(new java.awt.Dimension(40, 30));
        jButton9.setPreferredSize(new java.awt.Dimension(50, 30));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        add(jButton9);

        jButton10.setBackground(getBackground());
        jButton10.setText("MS");
        jButton10.setBorder(null);
        jButton10.setMaximumSize(new java.awt.Dimension(200, 200));
        jButton10.setMinimumSize(new java.awt.Dimension(40, 30));
        jButton10.setPreferredSize(new java.awt.Dimension(50, 30));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        add(jButton10);

        jButton11.setBackground(getBackground());
        jButton11.setText("M▼");
        jButton11.setBorder(null);
        jButton11.setMaximumSize(new java.awt.Dimension(200, 200));
        jButton11.setMinimumSize(new java.awt.Dimension(40, 30));
        jButton11.setPreferredSize(new java.awt.Dimension(50, 30));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        add(jButton11);

        jPanel1.setMaximumSize(new java.awt.Dimension(1000, 60));
        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        clearAllMemory();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        memoryAdd();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        memoryRecall();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        memoryStore();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        memoryPanel.getParent().remove(memoryPanel);
        jDialog1.add(memoryPanel);
        jDialog1.setLocationRelativeTo(this);
        jDialog1.setBounds(getX(), getY(), getWidth(), 200);
        jDialog1.setLocation(0, 0);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        memorySubstract();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jDialog1WindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialog1WindowLostFocus
        jDialog1.dispose();
    }//GEN-LAST:event_jDialog1WindowLostFocus


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
