package com.calculator;

import com.Tokenizing.TokenList;
import java.util.ArrayList;
import javax.swing.BoxLayout;
import javax.swing.JPanel;

/**
 *
 * @author AW Developer
 */
public class CommonKeyPanel extends javax.swing.JPanel {

    ButtonList buttons;
    ArrayList<JPanel> blocks;
    CommonNumberPanel parentText;

    /**
     * Creates new form CommonKeyPanel
     */
    public CommonKeyPanel(CommonNumberPanel parent, TokenList buttons, String pattern, int layout) {
        initComponents();
        blocks = new ArrayList<>();
        parentText = parent;
        this.buttons = new ButtonList(buttons, pattern, layout);
        setButtons();
    }

    public final void setButtons() {
        int layout = 0;
        int blockLength = 0;
        switch (buttons.getLayout()) {
            case ButtonLayout.COLUMN:
                layout = javax.swing.BoxLayout.LINE_AXIS;
                blockLength = buttons.width;
                break;
            case ButtonLayout.ROW:
                layout = javax.swing.BoxLayout.PAGE_AXIS;
                blockLength = buttons.height;
                break;
            default:
                break;
        }
        setLayout(new javax.swing.BoxLayout(this, layout));
        for (int i = 0; i < blockLength; i++) {
            JPanel p = new JPanel();
            p.setLayout(new BoxLayout(p, layout == BoxLayout.PAGE_AXIS ? BoxLayout.LINE_AXIS : BoxLayout.PAGE_AXIS));
            blocks.add(p);
        }
        blockLength = blockLength == buttons.width ? buttons.height : buttons.width;
        for (JPanel block : blocks) {
            for (int i = 0; i < blockLength; i++) {
                CommonKey b = buttons.getNextKey();
                if (b != null) {
                    b.setParentTextField(parentText);
                    block.add(b);
                } else {
                    blocks.get(i).add(new EmptyFiller());
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        row3 = new javax.swing.JPanel();
        row2 = new javax.swing.JPanel();
        row1 = new javax.swing.JPanel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        row3.setLayout(new javax.swing.BoxLayout(row3, javax.swing.BoxLayout.PAGE_AXIS));
        add(row3);

        row2.setLayout(new javax.swing.BoxLayout(row2, javax.swing.BoxLayout.Y_AXIS));
        add(row2);

        row1.setLayout(new javax.swing.BoxLayout(row1, javax.swing.BoxLayout.PAGE_AXIS));
        add(row1);
    }// </editor-fold>//GEN-END:initComponents

    class EmptyFiller extends JPanel {

        public EmptyFiller() {
            setMaximumSize(new java.awt.Dimension(1000, 1000));
            setMinimumSize(new java.awt.Dimension(40, 30));
            setPreferredSize(new java.awt.Dimension(70, 47));
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel row1;
    private javax.swing.JPanel row2;
    private javax.swing.JPanel row3;
    // End of variables declaration//GEN-END:variables
}
