package com.calculator;

/**
 *
 * @author AW Developer
 */
public class CommonMemoryPanel extends javax.swing.JPanel {

    MemoryPanel memory;
    CommonNumberPanel number;

    /**
     * Creates new form CommonMemoryPanel
     */
    public CommonMemoryPanel(MemoryPanel mp) {
        initComponents();
        memory = mp;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        memoryBar = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        memoryBar.setMaximumSize(new java.awt.Dimension(151516516, 50));
        memoryBar.setLayout(new javax.swing.BoxLayout(memoryBar, javax.swing.BoxLayout.LINE_AXIS));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setText("MC");
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(calculator.getBackground()));
        jButton6.setMaximumSize(new java.awt.Dimension(48, 30));
        jButton6.setMinimumSize(new java.awt.Dimension(48, 30));
        jButton6.setPreferredSize(new java.awt.Dimension(48, 30));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        memoryBar.add(jButton6);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setText("M+");
        jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(calculator.getBackground()));
        jButton7.setMaximumSize(new java.awt.Dimension(48, 30));
        jButton7.setMinimumSize(new java.awt.Dimension(48, 30));
        jButton7.setPreferredSize(new java.awt.Dimension(48, 30));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        memoryBar.add(jButton7);

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.setText("MR");
        jButton8.setBorder(javax.swing.BorderFactory.createLineBorder(calculator.getBackground()));
        jButton8.setMaximumSize(new java.awt.Dimension(48, 30));
        jButton8.setMinimumSize(new java.awt.Dimension(48, 30));
        jButton8.setPreferredSize(new java.awt.Dimension(48, 30));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        memoryBar.add(jButton8);

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton9.setText("M-");
        jButton9.setBorder(javax.swing.BorderFactory.createLineBorder(calculator.getBackground()));
        jButton9.setMaximumSize(new java.awt.Dimension(48, 30));
        jButton9.setMinimumSize(new java.awt.Dimension(48, 30));
        jButton9.setPreferredSize(new java.awt.Dimension(48, 30));
        memoryBar.add(jButton9);

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton10.setText("MS");
        jButton10.setBorder(javax.swing.BorderFactory.createLineBorder(calculator.getBackground()));
        jButton10.setMaximumSize(new java.awt.Dimension(48, 30));
        jButton10.setMinimumSize(new java.awt.Dimension(48, 30));
        jButton10.setPreferredSize(new java.awt.Dimension(48, 30));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        memoryBar.add(jButton10);

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton11.setText("M▼");
        jButton11.setBorder(javax.swing.BorderFactory.createLineBorder(calculator.getBackground()));
        jButton11.setMaximumSize(new java.awt.Dimension(48, 30));
        jButton11.setMinimumSize(new java.awt.Dimension(48, 30));
        jButton11.setPreferredSize(new java.awt.Dimension(48, 30));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        memoryBar.add(jButton11);

        add(memoryBar);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        memoryBar.removeAll();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        setValue(MemoryPanel.memStore);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        MemoryPanel.memStore = value;
        memoryPanel.newCell(value);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed

    }//GEN-LAST:event_jButton11ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel memoryBar;
    // End of variables declaration//GEN-END:variables
}
