package com.calculator.standard;

import com.tokenizing.Token;
import static com.tokenizing.Token.*;
import com.tokenizing.TokenList;
import com.tokenizing.TokenType;
import com.calculator.commoncalculator.button.ButtonLayout;
import com.calculator.commoncalculator.CommonKeyPanel;
import com.calculator.commoncalculator.CommonNumberPanel;
import static com.calculator.commoncalculator.button.DefaultButtons.BACK;
import static com.calculator.commoncalculator.button.DefaultButtons.C;
import static com.calculator.commoncalculator.button.DefaultButtons.CE;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author AW Developer
 */
public class StandardKeyPanel extends javax.swing.JPanel {

    CommonKeyPanel keyPanel;
    CommonNumberPanel numberPanel;
    TokenList buttons = new TokenList(
            MODULO, CE, C, BACK,
            new Token(TokenType.FUNCTION_, "1/x", 'r'), SQUARED, SQUREROOT, DIVIDE, SEVEN, EIGHT, NINE, MULTIPLY, FOUR, FIVE, SIX, MINUS, ONE, TWO, THREE, PLUS,
            PLUS_OR_MINUS, ZERO, DOT, EQUAL);
    String pattern = ""
            + "####\n"
            + "####\n"
            + "####\n"
            + "####\n"
            + "####\n"
            + "####\n";

    /**
     * Creates new form StandardKeyPanel
     */
    public StandardKeyPanel(CommonNumberPanel numberPanel) {
        this.numberPanel = numberPanel;
        initComponents();
        try {
            keyPanel = new CommonKeyPanel(numberPanel, buttons, pattern, ButtonLayout.ROW);
        } catch (Exception ex) {
            Logger.getLogger(StandardKeyPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        add(keyPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(10000, 10000));
        setMinimumSize(new java.awt.Dimension(300, 300));
        setPreferredSize(new java.awt.Dimension(300, 300));
        setLayout(new java.awt.CardLayout(5, 5));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
