package com.calculator.standard;

import com.Tokenizing.Token;
import static com.Tokenizing.Token.*;
import com.Tokenizing.TokenList;
import com.Tokenizing.TokenType;
import com.calculator.ButtonLayout;
import com.calculator.CommonKeyPanel;
import com.calculator.CommonNumberPanel;
import java.awt.event.KeyEvent;

/**
 *
 * @author AW Developer
 */
public class StandardKeyPanel extends javax.swing.JPanel {

    
    CommonKeyPanel keyPanel;
    CommonNumberPanel numberPanel;
    TokenList buttons=new TokenList(
            MODULO,new Token(TokenType.SYMBOL,"CE",(char)KeyEvent.VK_DELETE),new Token(TokenType.SYMBOL,"C",(char)KeyEvent.VK_ESCAPE),new Token(TokenType.SYMBOL,"<x]",(char)KeyEvent.VK_BACK_SPACE),
    new Token(TokenType.FUNCTION_,"1/x",'r'),SQUARED,SQUREROOT,DIVIDE,SEVEN,EIGHT,NINE,MULTIPLY,FOUR,FIVE,SIX,MINUS,ONE,TWO,THREE,PLUS,
    new Token(TokenType.SYMBOL,"+/-",'`'),ZERO,DOT,EQUAL);
    String pattern=""
            + "####\n"
            + "####\n"
            + "####\n"
            + "####\n"
            + "####\n"
            + "####\n";
    /**
     * Creates new form StandardKeyPanel
     */
    public StandardKeyPanel() {
        initComponents();
        keyPanel=new CommonKeyPanel(numberPanel, buttons, pattern, ButtonLayout.COLUMN);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
