package com.calculator.standard;

import com.calculator.CommonKeyPanel;
import com.calculator.CommonMemoryPanel;
import com.calculator.CommonNumberPanel;

/**
 *
 * @author AW Developer
 */
public class StandardFrame extends javax.swing.JPanel {
        
    StandardNumberPanel numberPanel;
    StandardKeyPanel keyPanel;
    /**
     * Creates new form Standard
     */
    public StandardFrame() {
        initComponents();
        numberPanel=new StandardNumberPanel();
        keyPanel=new StandardKeyPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
