/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.calculator.graphing;

import com.main.FrontFrame;
import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.WindowFocusListener;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JToggleButton;
import javax.swing.border.LineBorder;

/**
 *
 * @author AW Developer
 */
public class LineOptions extends javax.swing.JDialog {

    private Color color;
    public LineOptions(JComponent parent, boolean modal) {
        super(new JFrame(), modal);
        initComponents();
        setLocationRelativeTo(parent);
        addWindowFocusListener(new WindowFocusListener() {
            @Override
            public void windowGainedFocus(java.awt.event.WindowEvent e) {
            }

            @Override
            public void windowLostFocus(java.awt.event.WindowEvent e) {
                dispose();
            }
        });
        revalidate();
        repaint();
    }
    
    @Override
    public void paintComponents(Graphics g){
        Graphics2D g2=(Graphics2D)g;
        super.paintComponents(g2);
        g2.setColor(Color.red);
        g2.fillRoundRect(0, 0, getPreferredSize().width, getPreferredSize().height, 10, 10);
        g2.setColor(color);
        g2.drawRoundRect(0, 0, getPreferredSize().width, getPreferredSize().height, 10, 10);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton15 = new javax.swing.JToggleButton();
        jToggleButton12 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        jToggleButton16 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton13 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton14 = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.CardLayout(20, 20));

        jPanel5.setAlignmentX(0.0F);
        jPanel5.setPreferredSize(new java.awt.Dimension(32767, 32767));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 20));

        jPanel2.setMaximumSize(new java.awt.Dimension(300, 200));
        jPanel2.setMinimumSize(new java.awt.Dimension(300, 200));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 200));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Line options");
        jPanel2.add(jLabel4);

        jLabel5.setText("Color");
        jPanel2.add(jLabel5);

        jPanel1.setAlignmentX(0.0F);
        jPanel1.setMaximumSize(new java.awt.Dimension(300, 90));
        jPanel1.setMinimumSize(new java.awt.Dimension(320, 80));
        jPanel1.setPreferredSize(new java.awt.Dimension(320, 80));

        jToggleButton1.setBackground(new java.awt.Color(51, 51, 255));
        jToggleButton1.setBorder(null);
        jToggleButton1.setPreferredSize(new java.awt.Dimension(35, 35));
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                colorButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                colorButtonMouseExcited(evt);
            }
        });
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setColor(evt);
            }
        });
        jPanel1.add(jToggleButton1);

        jToggleButton4.setBackground(new java.awt.Color(0, 107, 0));
        jToggleButton4.setBorder(null);
        jToggleButton4.setPreferredSize(new java.awt.Dimension(35, 35));
        jToggleButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                colorButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                colorButtonMouseExcited(evt);
            }
        });
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setColor(evt);
            }
        });
        jPanel1.add(jToggleButton4);

        jToggleButton9.setBackground(new java.awt.Color(249, 16, 26));
        jToggleButton9.setBorder(null);
        jToggleButton9.setPreferredSize(new java.awt.Dimension(35, 35));
        jToggleButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                colorButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                colorButtonMouseExcited(evt);
            }
        });
        jToggleButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setColor(evt);
            }
        });
        jPanel1.add(jToggleButton9);

        jToggleButton11.setBackground(new java.awt.Color(221, 177, 0));
        jToggleButton11.setBorder(null);
        jToggleButton11.setPreferredSize(new java.awt.Dimension(35, 35));
        jToggleButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                colorButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                colorButtonMouseExcited(evt);
            }
        });
        jToggleButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setColor(evt);
            }
        });
        jPanel1.add(jToggleButton11);

        jToggleButton3.setBackground(new java.awt.Color(29, 172, 149));
        jToggleButton3.setBorder(null);
        jToggleButton3.setPreferredSize(new java.awt.Dimension(35, 35));
        jToggleButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                colorButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                colorButtonMouseExcited(evt);
            }
        });
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setColor(evt);
            }
        });
        jPanel1.add(jToggleButton3);

        jToggleButton5.setBackground(new java.awt.Color(0, 186, 56));
        jToggleButton5.setBorder(null);
        jToggleButton5.setPreferredSize(new java.awt.Dimension(35, 35));
        jToggleButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                colorButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                colorButtonMouseExcited(evt);
            }
        });
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setColor(evt);
            }
        });
        jPanel1.add(jToggleButton5);

        jToggleButton15.setBackground(new java.awt.Color(255, 22, 108));
        jToggleButton15.setBorder(null);
        jToggleButton15.setPreferredSize(new java.awt.Dimension(35, 35));
        jToggleButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                colorButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                colorButtonMouseExcited(evt);
            }
        });
        jToggleButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setColor(evt);
            }
        });
        jPanel1.add(jToggleButton15);

        jToggleButton12.setBackground(new java.awt.Color(255, 96, 15));
        jToggleButton12.setBorder(null);
        jToggleButton12.setPreferredSize(new java.awt.Dimension(35, 35));
        jToggleButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                colorButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                colorButtonMouseExcited(evt);
            }
        });
        jToggleButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setColor(evt);
            }
        });
        jPanel1.add(jToggleButton12);

        jToggleButton10.setBackground(new java.awt.Color(102, 0, 204));
        jToggleButton10.setBorder(null);
        jToggleButton10.setPreferredSize(new java.awt.Dimension(35, 35));
        jToggleButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                colorButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                colorButtonMouseExcited(evt);
            }
        });
        jToggleButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setColor(evt);
            }
        });
        jPanel1.add(jToggleButton10);

        jToggleButton16.setBackground(new java.awt.Color(0, 102, 102));
        jToggleButton16.setBorder(null);
        jToggleButton16.setPreferredSize(new java.awt.Dimension(35, 35));
        jToggleButton16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                colorButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                colorButtonMouseExcited(evt);
            }
        });
        jToggleButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setColor(evt);
            }
        });
        jPanel1.add(jToggleButton16);

        jToggleButton8.setBackground(new java.awt.Color(153, 0, 102));
        jToggleButton8.setBorder(null);
        jToggleButton8.setPreferredSize(new java.awt.Dimension(35, 35));
        jToggleButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                colorButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                colorButtonMouseExcited(evt);
            }
        });
        jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setColor(evt);
            }
        });
        jPanel1.add(jToggleButton8);

        jToggleButton13.setBackground(new java.awt.Color(153, 102, 0));
        jToggleButton13.setBorder(null);
        jToggleButton13.setPreferredSize(new java.awt.Dimension(35, 35));
        jToggleButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                colorButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                colorButtonMouseExcited(evt);
            }
        });
        jToggleButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setColor(evt);
            }
        });
        jPanel1.add(jToggleButton13);

        jToggleButton7.setBackground(new java.awt.Color(53, 53, 53));
        jToggleButton7.setBorder(null);
        jToggleButton7.setPreferredSize(new java.awt.Dimension(35, 35));
        jToggleButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                colorButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                colorButtonMouseExcited(evt);
            }
        });
        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setColor(evt);
            }
        });
        jPanel1.add(jToggleButton7);

        jToggleButton14.setBackground(new java.awt.Color(0, 0, 0));
        jToggleButton14.setBorder(null);
        jToggleButton14.setPreferredSize(new java.awt.Dimension(35, 35));
        jToggleButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                colorButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                colorButtonMouseExcited(evt);
            }
        });
        jToggleButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setColor(evt);
            }
        });
        jPanel1.add(jToggleButton14);

        jPanel2.add(jPanel1);

        jLabel6.setText("Style");
        jPanel2.add(jLabel6);

        jComboBox1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "______________", "--------------", "........................" }));
        jComboBox1.setAlignmentX(0.0F);
        jComboBox1.setMaximumSize(new java.awt.Dimension(200, 34));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1);

        jPanel5.add(jPanel2);

        getContentPane().add(jPanel5, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        setStyle(jComboBox1.getSelectedItem().toString().charAt(0));
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void setColor(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setColor
        JToggleButton btn = (JToggleButton) evt.getSource();
        color = btn.getBackground();
        for (Component comp : jPanel1.getComponents()) {
            JToggleButton btn1 = (JToggleButton) comp;
            btn1.setSelected(false);
        }
        btn.setBorder(new LineBorder(FrontFrame.APP_HOVER,2));
        setColor(color);
    }//GEN-LAST:event_setColor

    private void colorButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorButtonMouseEntered
        ((JComponent) evt.getSource()).setBorder(new LineBorder(FrontFrame.APP_HOVER));
        ((JComponent) evt.getSource()).setBorder(null);
    }//GEN-LAST:event_colorButtonMouseEntered

    private void colorButtonMouseExcited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorButtonMouseExcited
        // TODO add your handling code here:
    }//GEN-LAST:event_colorButtonMouseExcited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LineOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LineOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LineOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LineOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LineOptions dialog = new LineOptions(new JPanel(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    // End of variables declaration//GEN-END:variables

    public void setColor(Color color) {
    }

    public void setStyle(char charAt) {
    }

    
    public char getStyle(){
        return ((String)jComboBox1.getSelectedItem()).charAt(0);
    }
    
    public Color getColor(){
        return color;
    }
}
