package com.calculator.commoncalculator.history;

import com.tokenizing.TokenList;
import com.calculate.number.CNumber;
import com.calculator.commoncalculator.Ui;
import java.awt.Color;

/**
 *
 * @author AW Developer
 */
public abstract class HistoryCell extends javax.swing.JPanel {

    TokenList equation;
    CNumber answer;

    /**
     * Creates new form HistoryCell
     */
    public HistoryCell(TokenList equation, CNumber answer) {
        initComponents();
        this.equation = equation;
        this.answer = answer;
        setItem();
        java.awt.event.MouseAdapter listner = new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseEnter();
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseExit();
            }
            public void mouseClicked(java.awt.event.MouseEvent evt){
                historyItemClicked(equation, answer);
            }
        };
        jTextArea1.addMouseListener(listner);
        jTextArea2.addMouseListener(listner);
    }

    public void setItem() {
        jTextArea1.setText("kwhf8765676565567576584");
        jTextArea2.setText("44444 44444444 44444 433 33333338 7656 765 6556757 6584");
    }

    public abstract void historyItemClicked(TokenList equation, CNumber answer);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextArea2 = new javax.swing.JTextArea();
        jTextArea1 = new javax.swing.JTextArea();

        setMaximumSize(new java.awt.Dimension(300, 1000));
        setMinimumSize(new java.awt.Dimension(230, 100));
        setPreferredSize(new java.awt.Dimension(230, 100));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        setLayout(new java.awt.CardLayout(5, 5));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(1);
        jTextArea2.setText("0");
        jTextArea2.setWrapStyleWord(true);
        jTextArea2.setAlignmentX(0.0F);
        jTextArea2.setBorder(null);
        jTextArea2.setEnabled(false);
        jTextArea2.setMaximumSize(new java.awt.Dimension(300, 1000));
        jTextArea2.setMinimumSize(new java.awt.Dimension(300, 50));
        jTextArea2.setPreferredSize(new java.awt.Dimension(300, 50));
        jPanel1.add(jTextArea2);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(1);
        jTextArea1.setText("0");
        jTextArea1.setAlignmentX(0.0F);
        jTextArea1.setMaximumSize(new java.awt.Dimension(300, 100));
        jTextArea1.setMinimumSize(new java.awt.Dimension(300, 50));
        jTextArea1.setPreferredSize(new java.awt.Dimension(300, 50));
        jTextArea1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextArea1MouseClicked(evt);
            }
        });
        jPanel1.add(jTextArea1);

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        int h1 = Ui.wrapHeight(jTextArea1);
        int h2 = Ui.wrapHeight(jTextArea2);
        if (h1 != -1 && h2 != -1) {
            Ui.setSize(jTextArea1, 300, h1 + 30);
            Ui.setSize(jTextArea2, 300, h2 + 20);
            Ui.setSize(this, 320, h1 + h2 + 60);
        }
    }//GEN-LAST:event_formComponentResized

    private void jTextArea1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextArea1MouseClicked

    public void mouseEnter() {
        Color c = Ui.APP_HOVER;
        jTextArea1.setBackground(c);
        jTextArea2.setBackground(c);
        jPanel1.setBackground(c);
    }

    public void mouseExit() {
        jTextArea1.setBackground(getBackground());
        jTextArea2.setBackground(getBackground());
        jPanel1.setBackground(getBackground());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
