package com.calculator.programmer.functions;

import static com.amath.advacedmath.tokenizing.Token.AND;
import static com.amath.advacedmath.tokenizing.Token.NAND;
import static com.amath.advacedmath.tokenizing.Token.NOR;
import static com.amath.advacedmath.tokenizing.Token.NOT;
import static com.amath.advacedmath.tokenizing.Token.OR;
import static com.amath.advacedmath.tokenizing.Token.XOR;
import com.amath.advacedmath.tokenizing.TokenList;
import com.calculator.commoncalculator.button.ButtonLayout;
import com.calculator.commoncalculator.CommonKeyPanel;
import com.calculator.commoncalculator.CommonNumberPanel;
import com.calculator.ui.Ui;
import com.calculator.commoncalculator.popupPanel.PopupButton;
import com.calculator.commoncalculator.popupPanel.PopupPanel;
import java.util.logging.Level;
import java.util.logging.Logger;

public class FunctionsPanel extends javax.swing.JPanel {

    CommonKeyPanel bitwise;
    PopupPanel bitwiseDialog;
    PopupButton bitwiseButton;
    PopupPanel bitshiftDialog;
    PopupButton bitshiftButton;

    public FunctionsPanel(CommonNumberPanel numberPanel) {
        initComponents();
        try {
            bitwise = new CommonKeyPanel(numberPanel, new TokenList(AND, OR, NOT, NAND, NOR, XOR), "###\n###", ButtonLayout.ROW);
            Ui.setSize(bitwise, 180, 100);
        } catch (Exception ex) {
            Logger.getLogger(FunctionsPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        bitwiseDialog = new PopupPanel();
        bitshiftDialog = new PopupPanel();
        Ui.setSize(bitwiseDialog, 180, 100);
        Ui.setSize(bitshiftDialog, 180, 100);
        bitwiseButton = new PopupButton(bitwiseDialog, PopupButton.ALIGN_RIGHT, "Bitwise ▼");
        bitshiftButton = new PopupButton(bitshiftDialog, PopupButton.ALIGN_CENTER, "Bitshift ▼");
        bitwiseButton.setBorder(null);
        bitshiftButton.setBorder(null);
        Ui.setSize(bitwiseButton, 120, 30);
        Ui.setSize(bitshiftButton, 120, 30);
        add(bitwiseButton);
        add(bitshiftButton);
        bitwiseDialog.addComponent(bitwise);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bitshift = new javax.swing.JPopupMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem4 = new javax.swing.JRadioButtonMenuItem();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Arithmetic Shift");
        bitshift.add(jRadioButtonMenuItem1);

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("Logical Shift");
        bitshift.add(jRadioButtonMenuItem2);

        jRadioButtonMenuItem3.setSelected(true);
        jRadioButtonMenuItem3.setText("Rotate Circular Shift");
        bitshift.add(jRadioButtonMenuItem3);

        jRadioButtonMenuItem4.setSelected(true);
        jRadioButtonMenuItem4.setText("Rotate through Carry Circular Shift");
        bitshift.add(jRadioButtonMenuItem4);

        setMaximumSize(new java.awt.Dimension(10000, 40));
        setMinimumSize(new java.awt.Dimension(310, 40));
        setPreferredSize(new java.awt.Dimension(310, 40));
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu bitshift;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem4;
    // End of variables declaration//GEN-END:variables
}
