package com.calculator.programmer.functions;

import Programmer.Base;
import java.util.ArrayList;

/**
 *
 * @author AW Developer
 */
public final class RadixSelector extends javax.swing.JPanel {

    RadixButton hexButton;
    RadixButton decButton;
    RadixButton octButton;
    RadixButton binButton;

    /**
     * Creates new form RadixSelector
     */
    public RadixSelector() {
        initComponents();
        hexButton = new RadixButton(Base.HEX) {
            @Override
            public void choosed(Base radix) {
                setRadix(radix);
            }
        };
        decButton = new RadixButton(Base.DEC) {
            @Override
            public void choosed(Base radix) {
                setRadix(radix);
            }
        };
        octButton = new RadixButton(Base.OCT) {
            @Override
            public void choosed(Base radix) {
                setRadix(radix);
            }
        };
        binButton = new RadixButton(Base.BIN) {
            @Override
            public void choosed(Base radix) {
                setRadix(radix);
            }
        };
        add(hexButton);
        add(decButton);
        add(octButton);
        add(binButton);
        setRadix(Base.DEC);
    }

    public void setRadix(Base radix) {
        ArrayList<RadixButton> l = new ArrayList<>();
        l.add(hexButton);
        l.add(decButton);
        l.add(octButton);
        l.add(binButton);
        for (RadixButton b : l) {
            if (b.radix == radix) {
                b.selected();
            }else{
                b.deselected();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(102, 102, 0));
        setAlignmentX(0.5F);
        setAlignmentY(0.0F);
        setMaximumSize(new java.awt.Dimension(10000, 1000));
        setMinimumSize(new java.awt.Dimension(300, 120));
        setPreferredSize(new java.awt.Dimension(300, 120));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
