package com.calculator.programmer.functions;

import com.amath.advacedmath.calculate.CNumber;
import com.amath.advacedmath.calculate.NumberFormat;
import com.amath.advacedmath.programmer.Base;
import com.calculator.ui.Ui;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;

public abstract class RadixButton extends javax.swing.JPanel {

    Base radix;

    public RadixButton(Base radix) {
        initComponents();
        mouseExit();
        jLabel1.setText(radix.name());
        this.radix = radix;
        java.awt.event.MouseAdapter listner = new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseEnter();
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseExit();
            }

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                choosed(radix);
            }
        };
        jTextArea1.addMouseListener(listner);
        addMouseListener(listner);
        jSeparator1.addMouseListener(listner);
    }

    public abstract void choosed(Base radix);

    public void selected() {
        jSeparator1.setForeground(Ui.SPECIAL_COLOR);
    }

    public void deselected() {
        jSeparator1.setForeground(getBackground());
    }

    public void setNumber(CNumber n) {
        String s;
        try {
            s = n.setNumberFormat(NumberFormat.getGroupingNumberFormat(radix)).getNumberString();
            jTextArea1.setText(s);
//        System.out.println(s);
        } catch (Exception ex) {
            Logger.getLogger(RadixButton.class.getName()).log(Level.SEVERE, null, ex);
        }
//        setBoundsRelativeToText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jTextArea1 = new javax.swing.JTextArea();

        jMenuItem1.setText("COPY");
        jPopupMenu1.add(jMenuItem1);

        setAlignmentX(0.0F);
        setAlignmentY(1.0F);
        setMaximumSize(new java.awt.Dimension(10000, 40));
        setMinimumSize(new java.awt.Dimension(300, 20));
        setPreferredSize(new java.awt.Dimension(300, 20));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setAlignmentX(0.0F);
        jSeparator1.setMaximumSize(new java.awt.Dimension(7, 15));
        jSeparator1.setMinimumSize(new java.awt.Dimension(7, 15));
        jSeparator1.setPreferredSize(new java.awt.Dimension(7, 15));
        add(jSeparator1);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel1.setText("DEC");
        jLabel1.setMaximumSize(new java.awt.Dimension(30, 30));
        jLabel1.setMinimumSize(new java.awt.Dimension(50, 20));
        jLabel1.setPreferredSize(new java.awt.Dimension(30, 30));
        add(jLabel1);

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("0");
        jTextArea1.setAlignmentX(0.0F);
        jTextArea1.setMargin(new java.awt.Insets(6, 2, 6, 10));
        jTextArea1.setMaximumSize(new java.awt.Dimension(10000, 100));
        jTextArea1.setMinimumSize(new java.awt.Dimension(300, 20));
        jTextArea1.setPreferredSize(new java.awt.Dimension(300, 100));
        add(jTextArea1);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
//        setBoundsRelativeToText();
    }//GEN-LAST:event_formComponentResized
    public void mouseEnter() {
        Color c = Ui.APP_HOVER;
        jTextArea1.setBackground(c);
        setBackground(c);
    }

    public final void mouseExit() {
        Color c = (Color) UIManager.get("Panel.background");
        jTextArea1.setBackground(c);
        setBackground(c);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    private void setBoundsRelativeToText() {
        int h = Ui.wrapHeight(jTextArea1);
        if (h != -1) {
            Ui.setSize(jTextArea1, jTextArea1.getWidth(), h + 12);
            Ui.setSize(this, getWidth(), h + 20);
//            System.out.println(jTextArea1.getSize());
        }
    }
}
