package com.calculator.programmer;

import javax.swing.BoxLayout;
import javax.swing.JPanel;

/**
 *
 * @author AW Developer
 */
public class BitKeyPanel extends javax.swing.JPanel {

    QuadrantBitKeyPanel[][] fourBitKeys = new QuadrantBitKeyPanel[4][4];

    /**
     * Creates new form BitKeyPanel
     */
    public BitKeyPanel() {
        initComponents();
        for (int i = 0; i <= 64; i += 4) {
            fourBitKeys[i / 16][i / 4] = new QuadrantBitKeyPanel(i);
        }
        for (int i = 4; i >= 0; i--) {
            QuadrantBitKeyPanel[] qbps = fourBitKeys[i];
            JPanel p = new JPanel();
            p.setLayout(new BoxLayout(p, BoxLayout.LINE_AXIS));
            for (int j = 4; j >= 0; j--) {
                QuadrantBitKeyPanel qbp = qbps[j];
                p.add(qbp);
            }
            add(p);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
