package com.calculator.programmer;

import com.tokenizing.TokenList;
import com.calculate.CNumber;
import com.calculator.commonCalculator.Ui;
import com.calculator.commonCalculator.history.HistoryCell;
import com.calculator.commonCalculator.history.HistoryPanel;
import com.calculator.commonCalculator.memory.MemoryBar;
import com.calculator.commonCalculator.memory.MemoryCell;
import com.calculator.commonCalculator.memory.MemoryPanel;
import com.calculator.programmer.functions.RadixSelector;
import com.calculator.programmer.functions.FunctionsPanel;
import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JSeparator;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author AW Developer
 */
public class ProgrammerFrame extends javax.swing.JPanel {

    public ProgrammerNumberPanel numberPanel;
    public RadixSelector radixSelector;
    public FunctionsPanel functionsPanel;
    public ProgrammerKeyPanel keyPanel;
    public MemoryPanel memoryPanel;
    public MemoryBar memoryBar;

    /**
     * Creates new form Standard
     */
    public ProgrammerFrame() {
        initComponents();
        numberPanel = new ProgrammerNumberPanel(Boolean.TRUE) {
            @Override
            public void addHistory(TokenList equation, CNumber answer) {
            }
        };
        functionsPanel=new FunctionsPanel(numberPanel);
        keyPanel = new ProgrammerKeyPanel(numberPanel);
        memoryPanel = new MemoryPanel();
        radixSelector=new RadixSelector();
        memoryBar=new MemoryBar(memoryPanel, numberPanel);
        jTabbedPane1.add("Memory",memoryPanel);
        mainPanel.add(numberPanel);
        mainPanel.add(radixSelector);
        mainPanel.add(memoryBar);
        JSeparator seperater = new JSeparator(SwingConstants.HORIZONTAL);
        Ui.setSize(seperater, 10000, 10);
        mainPanel.add(seperater);
        mainPanel.add(functionsPanel);
        mainPanel.add(keyPanel);
        numberPanel.setAlignmentY(0.f);
        memoryBar.setAlignmentY(0.f);
        keyPanel.setAlignmentY(0.f);
    }

    public void newMemory(CNumber n) {
        memoryPanel.newMemory(new MemoryCell(n) {
            @Override
            public void memoryItemClicked(CNumber num) {
                numberPanel.setNumber(num);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidePanel = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jToolBar1 = new javax.swing.JToolBar();
        mainPanel = new javax.swing.JPanel();

        sidePanel.setMaximumSize(new java.awt.Dimension(300, 2147483647));
        sidePanel.setMinimumSize(new java.awt.Dimension(230, 600));
        sidePanel.setPreferredSize(new java.awt.Dimension(230, 600));
        sidePanel.setLayout(new java.awt.CardLayout());
        sidePanel.add(jTabbedPane1, "card2");

        jToolBar1.setRollover(true);
        jToolBar1.setBorderPainted(false);

        setAlignmentX(0.0F);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

        mainPanel.setMaximumSize(new java.awt.Dimension(10000, 10000));
        mainPanel.setMinimumSize(new java.awt.Dimension(300, 400));
        mainPanel.setPreferredSize(new java.awt.Dimension(300, 400));
        mainPanel.setLayout(new javax.swing.BoxLayout(mainPanel, javax.swing.BoxLayout.PAGE_AXIS));
        add(mainPanel);
    }// </editor-fold>//GEN-END:initComponents


    public static void main(String[] args) {
        try {
            UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(ProgrammerFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        Color background=new Color(30,30,30);
        Color background2=new Color(50,50,50);
        Color foreground=new Color(200,200,200);
        UIManager.put("Button.background", background2);
        UIManager.put("Button.foreground", foreground);
        UIManager.put("Button.focusedBorderColor", background);
        UIManager.put("TextField.foreground", foreground);
        UIManager.put("ToggleButton.foreground", foreground);
//        UIManager.put("Button.font", new Font("Dialog",1,18));
        UIManager.put("TextField.background", background);
        UIManager.put("ToggleButton.background", background);
        UIManager.put("ToggleButton.selectedBackground", new Color(0,8,10));
        UIManager.put("Panel.background", background);
        UIManager.put("Frame.background", background);
        ProgrammerFrame p = new ProgrammerFrame();
        JFrame frame = new JFrame("Common number field");
        frame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        frame.setBounds(200, 200, 300, 400);
        frame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        frame.getContentPane().setLayout(new javax.swing.BoxLayout(frame.getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));
        frame.getContentPane().add(p);
        frame.pack();
        new Thread(() -> {
            double d = 0;
            while (d < 300) {
                d++;
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(ProgrammerFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            System.exit(0);
        }).start();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            frame.setVisible(true);
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    public javax.swing.JPanel mainPanel;
    public javax.swing.JPanel sidePanel;
    // End of variables declaration//GEN-END:variables
}
