package com.calculator.programmer;

import static com.amath.advacedmath.tokenizing.Token.A;
import static com.amath.advacedmath.tokenizing.Token.B;
import static com.amath.advacedmath.tokenizing.Token.CLOSE_PRANTHESIS;
import static com.amath.advacedmath.tokenizing.Token.D;
import static com.amath.advacedmath.tokenizing.Token.DIVIDE;
import static com.amath.advacedmath.tokenizing.Token.DOT;
import static com.amath.advacedmath.tokenizing.Token.E;
import static com.amath.advacedmath.tokenizing.Token.EIGHT;
import static com.amath.advacedmath.tokenizing.Token.EQUAL;
import static com.amath.advacedmath.tokenizing.Token.F;
import static com.amath.advacedmath.tokenizing.Token.FIVE;
import static com.amath.advacedmath.tokenizing.Token.FOUR;
import static com.amath.advacedmath.tokenizing.Token.LSH;
import static com.amath.advacedmath.tokenizing.Token.MINUS;
import static com.amath.advacedmath.tokenizing.Token.MODULO;
import static com.amath.advacedmath.tokenizing.Token.MULTIPLY;
import static com.amath.advacedmath.tokenizing.Token.NINE;
import static com.amath.advacedmath.tokenizing.Token.ONE;
import static com.amath.advacedmath.tokenizing.Token.OPEN_PRANTHESIS;
import static com.amath.advacedmath.tokenizing.Token.PLUS;
import static com.amath.advacedmath.tokenizing.Token.PLUS_OR_MINUS;
import static com.amath.advacedmath.tokenizing.Token.RSH;
import static com.amath.advacedmath.tokenizing.Token.SEVEN;
import static com.amath.advacedmath.tokenizing.Token.SIX;
import static com.amath.advacedmath.tokenizing.Token.THREE;
import static com.amath.advacedmath.tokenizing.Token.TWO;
import static com.amath.advacedmath.tokenizing.Token.ZERO;
import com.amath.advacedmath.tokenizing.TokenList;
import com.calculator.commoncalculator.button.ButtonLayout;
import com.calculator.commoncalculator.CommonKeyPanel;
import com.calculator.commoncalculator.CommonNumberPanel;
import static com.calculator.commoncalculator.button.DefaultButtons.BACK;
import static com.calculator.commoncalculator.button.DefaultButtons.C;
import static com.calculator.commoncalculator.button.DefaultButtons.CE;
import java.util.logging.Level;
import java.util.logging.Logger;

public final class ProgrammerKeyPanel extends javax.swing.JPanel {

    CommonKeyPanel keyPanel;
    CommonNumberPanel numberPanel;
    TokenList buttons = new TokenList(A, LSH, RSH, CE, BACK,
            B, OPEN_PRANTHESIS, CLOSE_PRANTHESIS, MODULO, DIVIDE,
            C, SEVEN, EIGHT, NINE, MULTIPLY,
            D, FOUR, FIVE, SIX, MINUS,
            E, ONE, TWO, THREE, PLUS,
            F, PLUS_OR_MINUS, ZERO, DOT, EQUAL);
    String pattern = ""
            + "#####\n"
            + "#####\n"
            + "#####\n"
            + "#####\n"
            + "#####\n"
            + "#####\n";

    public ProgrammerKeyPanel(CommonNumberPanel numberPanel) {
        this.numberPanel = numberPanel;
        initComponents();
        try {
            keyPanel = new CommonKeyPanel(numberPanel, buttons, pattern, ButtonLayout.ROW);
        } catch (Exception ex) {
            Logger.getLogger(ProgrammerKeyPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        add(keyPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(10000, 10000));
        setMinimumSize(new java.awt.Dimension(300, 300));
        setPreferredSize(new java.awt.Dimension(300, 300));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
