package com.calculator.programmer;

import static com.tokenizing.Token.*;
import com.tokenizing.TokenList;
import com.calculator.commonCalculator.button.ButtonLayout;
import com.calculator.commonCalculator.CommonKeyPanel;
import com.calculator.commonCalculator.CommonNumberPanel;
import static com.calculator.commonCalculator.button.DefaultButtons.BACK;
import static com.calculator.commonCalculator.button.DefaultButtons.C;
import static com.calculator.commonCalculator.button.DefaultButtons.CE;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author AW Developer
 */
public final class ProgrammerKeyPanel extends javax.swing.JPanel {

    CommonKeyPanel keyPanel;
    CommonNumberPanel numberPanel;
    TokenList buttons = new TokenList(A,LSH,RSH,CE,BACK,
    B,OPEN_PRANTHESIS,CLOSE_PRANTHESIS,MODULO,DIVIDE,
    C,SEVEN,EIGHT,NINE,MULTIPLY,
    D,FOUR,FIVE,SIX,MINUS,
    E,ONE,TWO,THREE,PLUS,
    F,PLUS_OR_MINUS,ZERO,DOT,EQUAL);
    String pattern = ""
            + "#####\n"
            + "#####\n"
            + "#####\n"
            + "#####\n"
            + "#####\n"
            + "#####\n";

    /**
     * Creates new form StandardKeyPanel
     * @param numberPanel
     */
    public ProgrammerKeyPanel(CommonNumberPanel numberPanel) {
        this.numberPanel = numberPanel;
        initComponents();
        try {
            keyPanel = new CommonKeyPanel(numberPanel, buttons, pattern, ButtonLayout.ROW);
        } catch (Exception ex) {
            Logger.getLogger(ProgrammerKeyPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        add(keyPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(10000, 10000));
        setMinimumSize(new java.awt.Dimension(300, 300));
        setPreferredSize(new java.awt.Dimension(300, 300));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
